#include "WebPortal.h"

#include <ArduinoJson.h>
#include <WiFi.h>

#include "Config.h"
#include "Logger.h"

namespace {
const char PANEL_PAGE[] PROGMEM = R"rawliteral(
<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>СКУД</title>
<style>body{margin:0;background:#f1f3f5;color:#263238;font:14px Arial,sans-serif}header{background:#172b3a;color:#fff;padding:16px 22px}header strong{font-size:20px}nav{display:flex;gap:2px;background:#203d50;padding:0 14px;overflow:auto}nav button{border:0;background:transparent;color:#d7e3e8;padding:14px 16px;cursor:pointer;white-space:nowrap}nav button.active{background:#f1f3f5;color:#172b3a;border-top:3px solid #25a17b}main{max-width:1100px;margin:22px auto;padding:0 16px}.tab{display:none}.tab.active{display:block}.panel{background:#fff;border:1px solid #d9e0e4;margin-bottom:16px;padding:18px;box-shadow:0 1px 3px #0001}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:10px}.metric{background:#f5f7f8;border-left:4px solid #25a17b;padding:12px}.label{color:#65747c;font-size:12px}.value{font-weight:bold;margin-top:5px}label{display:block;margin:12px 0 5px;font-weight:bold}input,textarea,select{box-sizing:border-box;width:100%;padding:9px;border:1px solid #b8c4ca;border-radius:3px;font:inherit;background:#fff}textarea{min-height:260px}.row{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.row select{flex:1 1 240px;width:auto}.hidden{display:none}button.action{background:#1976a3;color:#fff;border:0;border-radius:3px;padding:10px 15px;cursor:pointer;margin-top:12px}button.action:disabled{opacity:.6}button.action.inline{margin-top:0;white-space:nowrap}pre{background:#172b3a;color:#d8e8ed;white-space:pre-wrap;padding:14px;max-height:520px;overflow:auto}.camera{max-width:100%;display:block;margin-top:12px}h2{margin-top:0;border-bottom:1px solid #e1e6e8;padding-bottom:10px}.hint{color:#65747c}</style></head>
<body><header><strong>СКУД</strong><div>Панель управления контроллером доступа</div></header>
<nav><button class="tab-button active" data-tab="status">Статус</button><button class="tab-button" data-tab="network">Сеть</button><button class="tab-button" data-tab="hotspot">Точка доступа</button><button class="tab-button" data-tab="hardware">Оборудование</button><button class="tab-button" data-tab="logs">Логи</button></nav>
<main><section id="status" class="tab active"><div class="panel"><h2>Общий статус</h2><div id="metrics" class="grid">%STATUS%</div></div><div class="panel"><h2>Сервер</h2><p id="server">%SERVER%</p></div></section>
<section id="network" class="tab"><div class="panel"><h2>Интернет и сервер</h2><form id="settings"><label>Wi-Fi сеть</label><div class="row"><select id="ssid-select"><option value="">Выберите сеть...</option></select><button id="scan" type="button" class="action inline">Сканировать</button></div><p id="scan-status" class="hint">Список доступных сетей подгружается автоматически.</p><p id="ssid-info" class="hint"></p><button id="wifi-test" type="button" class="action inline">Проверить подключение</button><p id="wifi-test-result" class="hint"></p><div id="manual-wrap" class="hidden"><label>Имя сети вручную</label><input id="ssid-manual" maxlength="32" placeholder="Скрытая или далёкая сеть"></div><input id="ssid-value" type="hidden" name="ssid" value="%SSID%"><label>Пароль Wi-Fi</label><input name="password" type="password" maxlength="64" value="%PASSWORD%"><label>URL сервера</label><input name="server" maxlength="192" required value="%SERVER_URL%"><label>Логин администратора</label><input name="admin_user" maxlength="32" required value="%ADMIN_USER%"><label>Пароль администратора</label><input name="admin_pass" type="password" maxlength="64" required value="%ADMIN_PASS%"><button class="action">Сохранить и перезапустить</button><p id="save-result" class="hint"></p></form></div></section>
<section id="hotspot" class="tab"><div class="panel"><h2>Точка доступа</h2><p class="hint">Настройки применятся после перезапуска при следующем входе в hotspot.</p><form id="settings-ap"><label>Имя точки доступа</label><input name="ap_ssid" maxlength="32" required value="%AP_SSID%"><label>Пароль точки доступа</label><input name="ap_pass" type="password" minlength="8" maxlength="64" required value="%AP_PASS%"><button class="action">Сохранить настройки</button><p id="ap-result" class="hint"></p></form></div></section>
<section id="hardware" class="tab"><div class="panel"><h2>Камера и считыватель</h2><button id="hw" class="action">Проверить оборудование</button><p id="hw-result">%HARDWARE%</p><label>Карта</label><p id="card-result">%CARD%</p><p class="hint">Считыватель работает постоянно, кнопка не нужна: новая карта отобразится сразу.</p><div class="row"><button id="stream" type="button" class="action inline">Запустить стрим</button><button id="photo" type="button" class="action inline">Получить изображение</button></div><p class="hint">Стрим автоматически останавливается через минуту. Пока он идёт, контроллер не читает карты и не проверяет доступ.</p><img id="camera" class="camera" alt="Изображение с камеры"></div></section>
<section id="logs" class="tab"><div class="panel"><h2>Журнал событий</h2><pre id="log-text">%LOGS%</pre></div></section></main>
<script>
var buttons=document.querySelectorAll('.tab-button');buttons.forEach(function(b){b.onclick=function(){buttons.forEach(function(x){x.classList.remove('active')});document.querySelectorAll('.tab').forEach(function(x){x.classList.remove('active')});b.classList.add('active');document.getElementById(b.dataset.tab).classList.add('active');};});
function refresh(){fetch('/api/status',{cache:'no-store'}).then(function(r){return r.json();}).then(function(x){document.getElementById('metrics').innerHTML=x.status;document.getElementById('server').textContent=x.server;document.getElementById('log-text').textContent=x.logs;var c=document.getElementById('card-result');if(c&&x.card)c.textContent=x.card;});}setInterval(refresh,2000);refresh();
function postForm(form,url,result){form.onsubmit=function(e){e.preventDefault();var b=form.querySelector('button');b.disabled=true;fetch(url,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(new FormData(form))}).then(function(r){return r.json();}).then(function(x){document.getElementById(result).textContent=x.result||x.error||'Сохранено';refresh();}).catch(function(){document.getElementById(result).textContent='Ошибка запроса';}).finally(function(){b.disabled=false;});};}postForm(document.getElementById('settings'),'/api/settings','save-result');postForm(document.getElementById('settings-ap'),'/api/settings','ap-result');
var MANUAL='__manual__';var ssidSelect=document.getElementById('ssid-select');var ssidValue=document.getElementById('ssid-value');var ssidManual=document.getElementById('ssid-manual');var manualWrap=document.getElementById('manual-wrap');var scanStatus=document.getElementById('scan-status');var ssidInfo=document.getElementById('ssid-info');var passwordField=document.getElementById('settings').querySelector('input[name=password]');var scanned=[];
function setSsid(v){ssidValue.value=v;updateSsidInfo();}
function describe(ssid){for(var i=0;i<scanned.length;i++){if(scanned[i].ssid===ssid)return scanned[i].ssid+' · '+scanned[i].rssi+' dBm · '+(scanned[i].secure?'защищённая':'открытая');}return ssid?'Сеть не найдена при сканировании, проверьте имя.':'';}
function updateSsidInfo(){var v=ssidValue.value;ssidInfo.textContent=v?v===MANUAL?'':describe(v):'';}
function showManual(value){ssidSelect.value=MANUAL;manualWrap.classList.remove('hidden');ssidManual.value=value&&value!==MANUAL?value:'';setSsid(ssidManual.value);}
function pickSsid(ssid){for(var i=0;i<ssidSelect.options.length;i++){if(ssidSelect.options[i].value===ssid){ssidSelect.selectedIndex=i;manualWrap.classList.add('hidden');setSsid(ssid);return;}}showManual(ssid);}
function loadNetworks(){var b=document.getElementById('scan');scanStatus.textContent='Сканирование сетей...';ssidSelect.disabled=true;b.disabled=true;fetch('/api/wifi-scan',{cache:'no-store'}).then(function(r){return r.json();}).then(function(x){var saved=ssidValue.value;var placeholder=document.createElement('option');placeholder.value='';placeholder.textContent='Выберите сеть...';var manualOption=document.createElement('option');manualOption.value=MANUAL;manualOption.textContent='Ввести имя вручную';ssidSelect.innerHTML='';ssidSelect.appendChild(placeholder);ssidSelect.appendChild(manualOption);scanned=x.networks||[];scanned.forEach(function(n){var e=document.createElement('option');e.value=n.ssid;e.textContent=n.ssid;ssidSelect.appendChild(e);});if(saved)pickSsid(saved);updateSsidInfo();scanStatus.textContent=x.count?('Найдено сетей: '+x.count):'Сети не найдены, укажите имя вручную.';}).catch(function(){scanStatus.textContent='Не удалось получить список сетей, попробуйте ещё раз.';}).finally(function(){ssidSelect.disabled=false;b.disabled=false;});}
ssidSelect.onchange=function(){if(ssidSelect.value===MANUAL){showManual(ssidValue.value);}else{manualWrap.classList.add('hidden');setSsid(ssidSelect.value);}};ssidManual.oninput=function(){setSsid(ssidManual.value);};document.getElementById('scan').onclick=loadNetworks;loadNetworks();
var testButton=document.getElementById('wifi-test');var testResult=document.getElementById('wifi-test-result');
function pollWifiTest(attempt){fetch('/api/wifi-test-status',{cache:'no-store'}).then(function(r){return r.json();}).then(function(x){if(x.state==='running'){if(attempt<90){setTimeout(function(){pollWifiTest(attempt+1);},1000);}else{testResult.textContent='Проверка не завершилась вовремя';testButton.disabled=false;}return;}testResult.textContent=x.message;testButton.disabled=false;}).catch(function(){if(attempt<90){setTimeout(function(){pollWifiTest(attempt+1);},2000);}else{testResult.textContent='Нет связи с контроллером';testButton.disabled=false;}});}
testButton.onclick=function(){var b=this;b.disabled=true;testResult.textContent='Проверяем подключение, это может занять до 20 секунд...';var body=new URLSearchParams();body.set('ssid',ssidValue.value);body.set('password',passwordField.value);fetch('/api/wifi-test',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:body}).catch(function(){}).finally(function(){pollWifiTest(0);});};
document.getElementById('hw').onclick=function(){var b=this;b.disabled=true;fetch('/api/hardware-check',{method:'POST'}).then(function(r){return r.json();}).then(function(x){document.getElementById('hw-result').textContent=x.hardware;refresh();}).finally(function(){b.disabled=false;});};var streaming=false;document.getElementById('stream').onclick=function(){var b=this;var i=document.getElementById('camera');if(streaming){streaming=false;b.textContent='Запустить стрим';i.removeAttribute('src');return;}streaming=true;b.textContent='Остановить стрим';i.src='/api/camera-stream?t='+Date.now();};document.getElementById('photo').onclick=function(){var b=this;if(streaming)return;b.disabled=true;var i=document.getElementById('camera');i.onload=function(){b.disabled=false};i.onerror=function(){b.disabled=false};i.src='/api/camera.jpg?t='+Date.now();};
</script></body></html>)rawliteral";
}

void WebPortal::registerRoutes() {
  webServer_.on("/", HTTP_GET, [this]() { handleRoot(); });
  webServer_.on("/api/status", HTTP_GET, [this]() { handleStatusApi(); });
  webServer_.on("/api/settings", HTTP_POST, [this]() { handleSave(); });
  webServer_.on("/api/hardware-check", HTTP_POST, [this]() { handleHardwareCheck(); });
  webServer_.on("/api/card-read", HTTP_POST, [this]() { handleCardRead(); });
  webServer_.on("/api/camera.jpg", HTTP_GET, [this]() { handleCamera(); });
webServer_.on("/api/camera-stream", HTTP_GET, [this]() { handleCameraStream(); });
  webServer_.on("/api/wifi-scan", HTTP_GET, [this]() { handleWifiScan(); });
webServer_.on("/api/wifi-test", HTTP_POST, [this]() { handleWifiTest(); });
webServer_.on("/api/wifi-test-status", HTTP_GET, [this]() { handleWifiTestStatus(); });
  webServer_.onNotFound([this]() { webServer_.send(204); });
}

void WebPortal::beginHotspot(ConfigManager& config) { config_ = &config; captiveMode_ = true; WiFi.mode(WIFI_AP_STA); IPAddress ip; ip.fromString(Config::AP_IP); WiFi.softAPConfig(ip, ip, IPAddress(255,255,255,0)); WiFi.softAP(config.apSsid().c_str(), config.apPassword().c_str(), Config::AP_CHANNEL); dnsServer_.start(53, "*", WiFi.softAPIP()); registerRoutes(); webServer_.begin(); }
void WebPortal::beginNormal(ConfigManager& config) { config_ = &config; captiveMode_ = false; WiFi.mode(WIFI_STA); registerRoutes(); webServer_.begin(); }
void WebPortal::setHardwareCheckHandler(HardwareCheckHandler handler){hardwareCheckHandler_=handler;} void WebPortal::setCardReadHandler(CardReadHandler handler){cardReadHandler_=handler;} void WebPortal::setCameraHandler(CameraHandler handler){cameraHandler_=handler;} void WebPortal::setCameraFrameHandler(CameraFrameHandler handler){cameraFrameHandler_=handler;} void WebPortal::setWifiScanHandler(WifiScanHandler handler){wifiScanHandler_=handler;} void WebPortal::setWifiTestHandler(WifiTestHandler handler){wifiTestHandler_=handler;} void WebPortal::setWifiTestStatusHandler(WifiTestStatusHandler handler){wifiTestStatusHandler_=handler;} void WebPortal::setCardState(const String& state){cardState_=state;} void WebPortal::setServerStatus(const String& status){serverStatus_=status;} void WebPortal::setRuntimeStatus(const String& status){runtimeStatus_=status;}
void WebPortal::update(){if(captiveMode_)dnsServer_.processNextRequest();webServer_.handleClient();}
String WebPortal::htmlEscape(const String& value) const {String x=value;x.replace("&","&amp;");x.replace("<","&lt;");x.replace(">","&gt;");x.replace("\"","&quot;");x.replace("'","&#39;");return x;}
String WebPortal::statusMetrics() const {String s="<div class=\"metric\"><div class=\"label\">Состояние</div><div class=\"value\">"+htmlEscape(runtimeStatus_)+"</div></div>";s+="<div class=\"metric\"><div class=\"label\">Wi-Fi</div><div class=\"value\">"+(WiFi.status()==WL_CONNECTED?String("Подключен"):String("Не подключен"))+"</div></div>";s+="<div class=\"metric\"><div class=\"label\">IP</div><div class=\"value\">"+WiFi.localIP().toString()+"</div></div>";s+="<div class=\"metric\"><div class=\"label\">Карта</div><div class=\"value\">"+htmlEscape(cardState_)+"</div></div>";s+="<div class=\"metric\"><div class=\"label\">Свободная память</div><div class=\"value\">"+String(ESP.getFreeHeap())+" байт</div></div>";return s;}
String WebPortal::renderPage() const {String p=FPSTR(PANEL_PAGE);String status=statusMetrics();p.replace("%STATUS%",status);p.replace("%SERVER%",htmlEscape(serverStatus_));p.replace("%SERVER_URL%",htmlEscape(config_->serverUrl()));p.replace("%SSID%",htmlEscape(config_->ssid()));p.replace("%PASSWORD%",htmlEscape(config_->password()));p.replace("%ADMIN_USER%",htmlEscape(config_->adminUsername()));p.replace("%ADMIN_PASS%",htmlEscape(config_->adminPassword()));p.replace("%AP_SSID%",htmlEscape(config_->apSsid()));p.replace("%AP_PASS%",htmlEscape(config_->apPassword()));p.replace("%HARDWARE%",htmlEscape(hardwareStatus_));p.replace("%CARD%",htmlEscape(cardState_));p.replace("%LOGS%",htmlEscape(Logger::getAllLogs()));return p;}

bool WebPortal::authenticate(){if(captiveMode_||webServer_.authenticate(config_->adminUsername().c_str(),config_->adminPassword().c_str()))return true;webServer_.requestAuthentication(BASIC_AUTH,"СКУД");return false;}
void WebPortal::handleRoot(){if(!authenticate())return;webServer_.send(200,"text/html; charset=utf-8",renderPage());}
void WebPortal::handleStatusApi(){if(!authenticate())return;String s=statusMetrics();JsonDocument d;d["status"]=s;d["card"]=cardState_;d["server"]=serverStatus_;d["logs"]=Logger::getAllLogs();String out;serializeJson(d,out);webServer_.send(200,"application/json",out);}
void WebPortal::handleHardwareCheck(){if(!authenticate())return;hardwareStatus_=hardwareCheckHandler_?hardwareCheckHandler_():"Проверка недоступна";JsonDocument d;d["hardware"]=hardwareStatus_;String o;serializeJson(d,o);webServer_.send(200,"application/json",o);}
void WebPortal::handleCardRead(){if(!authenticate())return;String x=cardReadHandler_?cardReadHandler_():"Считывание недоступно";JsonDocument d;d["card"]=x;String o;serializeJson(d,o);webServer_.send(200,"application/json",o);}
void WebPortal::handleCamera(){if(!authenticate()){return;}if(cameraHandler_)cameraHandler_(webServer_);else webServer_.send(503,"text/plain","Камера недоступна");}
void WebPortal::handleCameraStream(){if(!authenticate())return;if(!cameraFrameHandler_){webServer_.send(503,"text/plain","Камера недоступна");return;}Logger::info("Camera stream started");webServer_.sendHeader("Cache-Control","no-store");webServer_.send(200,"multipart/x-mixed-replace;boundary=frame");uint32_t startedAt=millis();while(cameraFrameHandler_(webServer_)){if(millis()-startedAt>=WebPortal::STREAM_MAX_MS){Logger::info("Camera stream stopped by time limit");break;}delay(WebPortal::STREAM_INTERVAL_MS);}}
void WebPortal::handleWifiTest(){if(!authenticate())return;if(!wifiTestHandler_){webServer_.send(503,"application/json","{\"result\":\"Проверка недоступна\"}");return;}String ssid=webServer_.hasArg("ssid")?webServer_.arg("ssid"):config_->ssid();String password=webServer_.hasArg("password")?webServer_.arg("password"):config_->password();wifiTestHandler_(ssid,password);webServer_.send(200,"application/json","{\"result\":\"Проверка запущена\"}");}
void WebPortal::handleWifiTestStatus(){if(!authenticate())return;String state="idle",message="Проверка не запускалась";if(wifiTestStatusHandler_)wifiTestStatusHandler_(state,message);JsonDocument d;d["state"]=state;d["message"]=message;String o;serializeJson(d,o);webServer_.send(200,"application/json",o);}
void WebPortal::handleWifiScan(){if(!authenticate())return;if(!wifiScanHandler_){webServer_.send(503,"application/json","{\"error\":\"Сканирование недоступно\"}");return;}if(scanCache_.length()>0&&millis()-lastScanAt_<NetworkService::SCAN_CACHE_MS){webServer_.send(200,"application/json",scanCache_);return;}NetworkService::WifiNetwork networks[NetworkService::SCAN_MAX_NETWORKS];size_t count=wifiScanHandler_(networks,NetworkService::SCAN_MAX_NETWORKS);JsonDocument d;JsonArray list=d["networks"].to<JsonArray>();for(size_t i=0;i<count;++i){JsonObject item=list.add<JsonObject>();item["ssid"]=networks[i].ssid;item["rssi"]=networks[i].rssi;item["secure"]=networks[i].secure;}d["count"]=count;String out;serializeJson(d,out);scanCache_=out;lastScanAt_=millis();Logger::info("Wi-Fi scan returned %u networks",static_cast<unsigned>(count));webServer_.send(200,"application/json",out);}
void WebPortal::handleSave(){if(!authenticate())return;String ssid=config_->ssid(),pass=config_->password(),server=config_->serverUrl(),user=config_->adminUsername(),adminPass=config_->adminPassword(),apSsid=config_->apSsid(),apPass=config_->apPassword();if(webServer_.hasArg("ssid"))ssid=webServer_.arg("ssid");if(webServer_.hasArg("password"))pass=webServer_.arg("password");if(webServer_.hasArg("server"))server=webServer_.arg("server");if(webServer_.hasArg("admin_user"))user=webServer_.arg("admin_user");if(webServer_.hasArg("admin_pass"))adminPass=webServer_.arg("admin_pass");if(webServer_.hasArg("ap_ssid"))apSsid=webServer_.arg("ap_ssid");if(webServer_.hasArg("ap_pass"))apPass=webServer_.arg("ap_pass");if(ssid.length()==0||server.length()==0||user.length()==0||adminPass.length()==0||apSsid.length()==0||apPass.length()<8){webServer_.send(400,"application/json","{\"result\":\"Некорректные параметры\"}");return;}if(!config_->save(ssid,pass,server,user,adminPass,apSsid,apPass)){webServer_.send(500,"application/json","{\"result\":\"Ошибка сохранения\"}");return;}webServer_.send(200,"application/json","{\"result\":\"Сохранено, контроллер перезапускается\"}");ESP.restart();}
